trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: '$(Build.BuildId)'

steps:
- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set region $(AWS_REGION)
  displayName: Configure AWS

- script: |
    aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
  displayName: Login ECR

- script: |
    IMAGE_URI="$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(imageTag)"
    docker build -t "$IMAGE_URI" .
  displayName: Build Docker

- script: |
    IMAGE_URI="$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(imageTag)"
    docker push "$IMAGE_URI"
  displayName: Push Image

- script: |
    aws ecs update-service \
      --cluster $(ECS_CLUSTER) \
      --service $(ECS_SERVICE) \
      --force-new-deployment
  displayName: Deploy ECS