trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: '$(Build.BuildId)'

steps:

- script: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  displayName: Install AWS CLI

- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set region $(AWS_REGION)
  displayName: Configure AWS

- script: |
    aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
  displayName: Login ECR

- script: |
    docker build -t ecs-demo .
    docker tag ecs-demo:latest $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(imageTag)
  displayName: Build Docker

- script: |
    docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(imageTag)
  displayName: Push Image

- script: |
    aws ecs update-service \
      --cluster $(ECS_CLUSTER) \
      --service $(ECS_SERVICE) \
      --force-new-deployment
  displayName: Deploy ECS